spring:
    resources:
        chain:
            cache: false
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
    mvc:
        throw-exception-if-no-handler-found: true
    datasource: 
        url: jdbc:postgresql://localhost:5432/bizwatch
        username: postgres
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1
        
app:
    name: CryptoBiz
    url: http://localhost:8080
    
